version: "3.8"

services:
  redis:
    container_name: redis-server
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  mysql:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/data:/etc/mysql/conf.d/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: r2db
      MYSQL_USER: r2svc
      MYSQL_PASSWORD: 123456
  pulsar:
    image: apachepulsar/pulsar:3.1.0
    container_name: pulsar-standalone
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ./data/pulsar/data:/pulsar/data
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
